#! /bin/sh

ssh -NTC \
    -o ServerAliveInterval=60 \
    -o ExitOnForwardFailure=yes \
    -o StrictHostKeyChecking=no \
    -R 8780:localhost:22 \
    -i bkf-key \
    -p 2221 \
    tunnel@k.pacew.org

