#! /bin/sh

exec >> /tmp/pace1 2>&1

while true
do
    date

    ssh -NTC \
	-o ServerAliveInterval=60 \
	-o ExitOnForwardFailure=yes \
	-o StrictHostKeyChecking=no \
	-R 8780:localhost:22 \
	-i /Users/pace/bkf/bkf-key \
	-p 2221 \
	tunnel@k.pacew.org

    date
    echo "ssh exited ... sleeping"

    sleep 10
done
